Repository caicloud/log-pilot, pull requests merged in 2019-07, with the labels that each got.

#22 fix(logstash): add logstash config
  assets/filebeat/filebeat.tpl
  build/filebeat/filebeat.yml.tpl
  pilot/configurer/configurer.go
  pilot/discovery/discovery.go
  release/logging-filebeat.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#23 feat(starbucks): set ignore_older confg
  assets/filebeat/filebeat.tpl
  build/filebeat/filebeat.yml.tpl
  pilot/configurer/configurer.go
  pilot/discovery/discovery.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#24 feat(*): enable filebeat statistic API
  build/filebeat/filebeat.yml.tpl
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#27 [STARBUCKS-17]fix(starbucks): drop log field when handle multiline message
  build/filebeat/filebeat.yml.tpl
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#30 fix(starbucks): change logstash host fields
  build/filebeat/filebeat.yml.tpl
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#31 feat(*): add priority class
  release/logging-filebeat.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
