Repository caicloud/log-pilot, pull requests merged in 2019-11, with the labels that each got.

#58 chore(release): adjust resource quota and remove pod priority
  release/logging-filebeat.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#62 chore(*): added Dockerfile for filebeat for compatibility
  build/filebeat-keeper/Makefile
  build/filebeat/Dockerfile
  build/filebeat/README.md
  build/filebeat/filebeat.yml.tpl
  build/filebeat/k8s-log-template.json
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#65 chore(OWNERS): added jianglinjian as an approver
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#66 [release-1.1] cherrypick beat-exporter
  Makefile
  build/filebeat-keeper/Dockerfile
  build/filebeat/Dockerfile
  build/log-pilot/Dockerfile
  release/logging-filebeat.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#67 fix: exclude "Cannot index message" error when gathering logs of Filebeat
  assets/filebeat/filebeat.tpl
  cmd/log-pilot/main.go
  pilot/configurer/filebeat/filebeat.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
