Repository caicloud/log-pilot, pull requests merged in 2020-03, with the labels that each got.

#81 refactor(release): remove Prometheus annotations and added a service
  release/logging-filebeat.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#76 [release-1.1] chore(filebeat): update filebeat version to v6.8.6
  build/filebeat-keeper/Dockerfile
  build/filebeat/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#88 chore(config): remove unuseful step in dockerfile && fix filebeat.yml.tpl
  build/filebeat-keeper/Dockerfile
  build/filebeat-keeper/filebeat.yml.tpl
  build/filebeat/Dockerfile
  build/filebeat/filebeat.yml.tpl
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#82 feat(release): upgrade beat-exporter to 0.3.1
  release/logging-filebeat.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#84 [release-1/starbucks] fix(filebeat): update filebeat version to v6.8.6
  build/filebeat-keeper/Dockerfile
  build/filebeat/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
